---
    
name: test-check

on: 
    push:
        branches:
            - source

jobs: 
    build: 
        runs-on: self-hosted

        defaults:
            run:
                working-directory: app

        strategy:
            matrix:
                node-version: [20.x]

        permissions:
            contents: write

        steps:
            - uses: actions/checkout@v3
              with:
                repository: elasticdog/transcrypt
                path: transcrypt
                # - run: ls -la
                # - run: cd transcrypt && ls -la
                # - run: ln -s ${PWD}/transcrypt/transcrypt /usr/local/bin/transcrypt


            - uses: actions/checkout@v3
              with: 
                path: app
            - run: ../transcrypt/transcrypt -y -p "${{ secrets.TRANSCRYPT_PASSWORD}}"
            - uses: actions/setup-node@v3
              with:
                cache-dependency-path: 'app/package-lock.json'
                node-version: 20
                cache: 'npm'

            - run: make install
            - run: make lint
            - run: make test

            # - name: setup git config
            - run: |
                git config user.name 'Bot'
                git config user.email '<>'
                
            - name: Prepare template
              run: |
                git checkout --orphan main source
                echo '' > index.js
                echo '' > .gitattributes
                git add -A
                git commit --no-verify -m 'Rebuild template (auto)'
                git push -f --no-verify --set-upstream origin main


